language: node_js
node_js:
  - "10.13.0"
cache:
  directories:
    - "node_modules"
env:
  global:
    - export NODE_ENV=test
    - CC_TEST_REPORTER_ID=11c2d48e7e01b9ffc155fd9d0c94c39a77ab2d882f75acfd5868d01752c770e6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
